# Generated by Django 4.2.4 on 2023-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_user_avatar_shop_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Customer', 'Customer'), ('Employee', 'Employee')], default='Customer', max_length=10, null=True),
        ),
    ]
