# Generated by Django 4.2.4 on 2023-08-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Seller', 'Seller'), ('Customer', 'Customer'), ('Employee', 'Employee')], default='Customer', max_length=10),
        ),
    ]
